### ISSUE TITLE
Sleeper leagues with teams that have no owners throws a TypeError

### ISSUE THREAD

**Issue by HappyZombies** [HappyZombies/ffawards.app#1]
```text
    TypeError: Cannot read properties of undefined (reading 'metadata')
        at _calculateSleeperAward (/var/task/src/awards/MostPositionPointsAward.js:47:44)
        at MostPositionPointsAward.calculateAward (/var/task/src/awards/MostPositionPointsAward.js:122:16)
        at AwardsService.generateDefaultLeagueAwards (/var/task/src/services/AwardsService.js:57:78)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async /var/task/src/api/routes/v1/dashboard.js:48:13
```

Reproduce:
Getting this error, the situation was a 11 player league in which the 12th player is a "bot" (at least that's what I am calling it, it's really an ownerless team) and as such, it doesn't have an owner.

It does have a name however, so we should fallback to this, but I think I will just skip these teams for now.

**Comment by HappyZombies** [comment]
This fixes removes any ownerless teams, is this what we want however? not sure still thinking about it and may revisit
